name: Build latex
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Pre.tex
        args: -jobname=my_doc -pdf --shell-escape -file-line-error -halt-on-error -interaction=nonstopmode
        compiler: latexmk
